In [1]:
import torch 
import numpy as np

# Empty Tensor

In [9]:
# Create a 3D tensor, without initialize

x = torch.empty(1, 2, 3) # the left value is the outer size
print(x)

tensor([[[3.0403e+01, 3.0781e-41, 2.3694e-38],
         [1.5909e-05, 0.0000e+00, 8.2403e-06]]])


# One Tensor

init all value to 1 

In [13]:
x = torch.ones(2, 3, dtype=torch.float16) # the left value is the outer size
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([2, 3])


# Creaet a concret tensor

In [14]:
x = torch.tensor([2.5, 0.1])
print(x.size())

torch.Size([2])


# Tensor operations

In [16]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x + y
print(z)

tensor([[0.5298, 0.0725],
        [0.9551, 0.9703]])
tensor([[0.9208, 0.7838],
        [0.4143, 0.2348]])
tensor([[1.4505, 0.8563],
        [1.3694, 1.2051]])


In [17]:
print(torch.add(x, y))

tensor([[1.4505, 0.8563],
        [1.3694, 1.2051]])


In pytorch fucntion end with _ means inplace opertion

In [18]:
print(y.add_(x))

tensor([[1.4505, 0.8563],
        [1.3694, 1.2051]])


In [21]:
y = torch.rand(2, 2)
print(torch.mul(x, y))

tensor([[0.2883, 0.0195],
        [0.8394, 0.3298]])


# Slice Tensor

In [25]:
x = torch.rand(5, 3)
print(x)

print(x[:, 0])

tensor([[0.2182, 0.8702, 0.1321],
        [0.9437, 0.3912, 0.0199],
        [0.6083, 0.9117, 0.1944],
        [0.3390, 0.6286, 0.3546],
        [0.8455, 0.1592, 0.9420]])
tensor([0.2182, 0.9437, 0.6083, 0.3390, 0.8455])


# Reshape

In [29]:
x = torch.rand(4, 4)
print(x)

y = x.view(16)
print(y)

z = x.view(2, 8)
print(z)

q = x.view(2, -1)
print(q)

tensor([[0.8221, 0.6166, 0.4571, 0.8171],
        [0.5131, 0.0293, 0.1076, 0.1066],
        [0.9641, 0.9710, 0.3124, 0.2648],
        [0.7722, 0.6301, 0.0129, 0.7310]])
tensor([0.8221, 0.6166, 0.4571, 0.8171, 0.5131, 0.0293, 0.1076, 0.1066, 0.9641,
        0.9710, 0.3124, 0.2648, 0.7722, 0.6301, 0.0129, 0.7310])
tensor([[0.8221, 0.6166, 0.4571, 0.8171, 0.5131, 0.0293, 0.1076, 0.1066],
        [0.9641, 0.9710, 0.3124, 0.2648, 0.7722, 0.6301, 0.0129, 0.7310]])
tensor([[0.8221, 0.6166, 0.4571, 0.8171, 0.5131, 0.0293, 0.1076, 0.1066],
        [0.9641, 0.9710, 0.3124, 0.2648, 0.7722, 0.6301, 0.0129, 0.7310]])


# Numpy and Tensor

## Tensor to numpy

In [30]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


**Be Careful  !!! In this way, the Numpy and Tensor using the same memory,change one value will also change the other one.**

In [31]:
a.add_(1) # remember funtion with _ means inplace operation
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Numpy to Tensor

In [35]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# You cannot conver a GPU tensor to numpy

In [7]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y

  print(z)

  # If you want to convert a GPU tensor, send it to CPU at first
  print(z.to("cpu").numpy())

  print(z.numpy())

tensor([2., 2., 2., 2., 2.], device='cuda:0')
[2. 2. 2. 2. 2.]


TypeError: ignored

# Gradient

In [8]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
